name: symbolic
description: "Symbolic mathematics library for Dart and Flutter. Algebra, calculus, etc."
version: 0.0.4
homepage: https://github.com/Sub6Resources/symbolic

environment:
  sdk: ^3.6.0

dependencies:
  rational: ^2.2.3

dev_dependencies:
  lints: ^5.1.1
  matcher: ^0.12.17
  test: ^1.25.15
