name: symbolic
description: "Symbolic mathematics library for Dart and Flutter. Algebra, calculus, etc."
version: 0.0.3
homepage: https://github.com/Sub6Resources/symbolic

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  lints: ^5.1.1
