name: symbolic
description: "Symbolic mathematics library for Dart."
version: 0.0.2
homepage: https://github.com/Sub6Resources/symbolic
issue_tracker: https://github.com/Sub6Resources/symbolic/issues

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  flutter_lints: ^5.0.0
